/* Generated By:JavaCC: Do not edit this line. FooParserConstants.java */
package com;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FooParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int EOR = 2;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int LETTER = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int BREAK = 7;
  /** RegularExpression Id. */
  int CLOSE = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int GOTO = 12;
  /** RegularExpression Id. */
  int HALT = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int JOB = 15;
  /** RegularExpression Id. */
  int KILL = 16;
  /** RegularExpression Id. */
  int LOCK = 17;
  /** RegularExpression Id. */
  int MERGE = 18;
  /** RegularExpression Id. */
  int NEW = 19;
  /** RegularExpression Id. */
  int OPEN = 20;
  /** RegularExpression Id. */
  int QUIT = 21;
  /** RegularExpression Id. */
  int READ = 22;
  /** RegularExpression Id. */
  int SET = 23;
  /** RegularExpression Id. */
  int USE = 24;
  /** RegularExpression Id. */
  int VIEW = 25;
  /** RegularExpression Id. */
  int WRITE = 26;
  /** RegularExpression Id. */
  int XECUTE = 27;
  /** RegularExpression Id. */
  int F_ASCII = 28;
  /** RegularExpression Id. */
  int F_CHAR = 29;
  /** RegularExpression Id. */
  int F_DATA = 30;
  /** RegularExpression Id. */
  int F_EXTRACT = 31;
  /** RegularExpression Id. */
  int F_FIND = 32;
  /** RegularExpression Id. */
  int F_FNUMBER = 33;
  /** RegularExpression Id. */
  int F_GET = 34;
  /** RegularExpression Id. */
  int F_JUSTIFY = 35;
  /** RegularExpression Id. */
  int F_LENGTH = 36;
  /** RegularExpression Id. */
  int F_NAME = 37;
  /** RegularExpression Id. */
  int F_ORDER = 38;
  /** RegularExpression Id. */
  int F_PIECE = 39;
  /** RegularExpression Id. */
  int F_QLENGTH = 40;
  /** RegularExpression Id. */
  int F_QSUBSCRIPT = 41;
  /** RegularExpression Id. */
  int F_QUERY = 42;
  /** RegularExpression Id. */
  int F_RANDOM = 43;
  /** RegularExpression Id. */
  int F_REVERSE = 44;
  /** RegularExpression Id. */
  int F_SELECT = 45;
  /** RegularExpression Id. */
  int F_STACK = 46;
  /** RegularExpression Id. */
  int F_TEXT = 47;
  /** RegularExpression Id. */
  int F_TRANSLATE = 48;
  /** RegularExpression Id. */
  int F_VIEW = 49;
  /** RegularExpression Id. */
  int V_DEVICE = 50;
  /** RegularExpression Id. */
  int V_ECODE = 51;
  /** RegularExpression Id. */
  int V_ESTACK = 52;
  /** RegularExpression Id. */
  int V_HORLOG = 53;
  /** RegularExpression Id. */
  int V_IO = 54;
  /** RegularExpression Id. */
  int V_JOB = 55;
  /** RegularExpression Id. */
  int V_KEY = 56;
  /** RegularExpression Id. */
  int V_PRINCIPAL = 57;
  /** RegularExpression Id. */
  int V_QUIT = 58;
  /** RegularExpression Id. */
  int V_REFERENCE = 59;
  /** RegularExpression Id. */
  int V_STORAGE = 60;
  /** RegularExpression Id. */
  int V_SYSTEM = 61;
  /** RegularExpression Id. */
  int V_TEST = 62;
  /** RegularExpression Id. */
  int V_X = 63;
  /** RegularExpression Id. */
  int V_Y = 64;
  /** RegularExpression Id. */
  int SV_CHARACTER = 65;
  /** RegularExpression Id. */
  int SV_DEVICE = 66;
  /** RegularExpression Id. */
  int SV_GLOBAL = 67;
  /** RegularExpression Id. */
  int SV_JOB = 68;
  /** RegularExpression Id. */
  int SV_LOCK = 69;
  /** RegularExpression Id. */
  int SV_ROUTINE = 70;
  /** RegularExpression Id. */
  int NAME = 71;
  /** RegularExpression Id. */
  int STRLIT = 72;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\\n\"",
    "\"\\r\\f\"",
    "<COMMENT>",
    "<LETTER>",
    "<NUMBER>",
    "<DIGIT>",
    "<BREAK>",
    "<CLOSE>",
    "<DO>",
    "<ELSE>",
    "<FOR>",
    "<GOTO>",
    "<HALT>",
    "<IF>",
    "<JOB>",
    "<KILL>",
    "<LOCK>",
    "<MERGE>",
    "<NEW>",
    "<OPEN>",
    "<QUIT>",
    "<READ>",
    "<SET>",
    "<USE>",
    "<VIEW>",
    "<WRITE>",
    "<XECUTE>",
    "<F_ASCII>",
    "<F_CHAR>",
    "<F_DATA>",
    "<F_EXTRACT>",
    "<F_FIND>",
    "<F_FNUMBER>",
    "<F_GET>",
    "<F_JUSTIFY>",
    "<F_LENGTH>",
    "<F_NAME>",
    "<F_ORDER>",
    "<F_PIECE>",
    "<F_QLENGTH>",
    "<F_QSUBSCRIPT>",
    "<F_QUERY>",
    "<F_RANDOM>",
    "<F_REVERSE>",
    "<F_SELECT>",
    "<F_STACK>",
    "<F_TEXT>",
    "<F_TRANSLATE>",
    "<F_VIEW>",
    "<V_DEVICE>",
    "<V_ECODE>",
    "<V_ESTACK>",
    "<V_HORLOG>",
    "<V_IO>",
    "<V_JOB>",
    "<V_KEY>",
    "<V_PRINCIPAL>",
    "<V_QUIT>",
    "<V_REFERENCE>",
    "<V_STORAGE>",
    "<V_SYSTEM>",
    "<V_TEST>",
    "\"$X\"",
    "\"$Y\"",
    "<SV_CHARACTER>",
    "<SV_DEVICE>",
    "<SV_GLOBAL>",
    "<SV_JOB>",
    "<SV_LOCK>",
    "<SV_ROUTINE>",
    "<NAME>",
    "<STRLIT>",
    "\" \"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&SQL\"",
    "\"@\"",
    "\":\"",
    "\"=\"",
    "\"^\"",
    "\"+\"",
    "\"\\\'\"",
    "\"?\"",
    "\"-\"",
    "\"_\"",
    "\"*\"",
    "\"/\"",
    "\"#\"",
    "\"\\\\\"",
    "\"**\"",
    "\"<\"",
    "\">\"",
    "\"]\"",
    "\"[\"",
    "\"]]\"",
    "\"&\"",
    "\"!\"",
  };

}
