/* Generated By:JavaCC: Do not edit this line. FooParserConstants.java */
package com;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FooParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int EOR = 2;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int NAME = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int EXTTEXT = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CLOSE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int GOTO = 13;
  /** RegularExpression Id. */
  int HALT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int JOB = 16;
  /** RegularExpression Id. */
  int KILL = 17;
  /** RegularExpression Id. */
  int LOCK = 18;
  /** RegularExpression Id. */
  int MERGE = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int OPEN = 21;
  /** RegularExpression Id. */
  int QUIT = 22;
  /** RegularExpression Id. */
  int READ = 23;
  /** RegularExpression Id. */
  int SET = 24;
  /** RegularExpression Id. */
  int USE = 25;
  /** RegularExpression Id. */
  int VIEW = 26;
  /** RegularExpression Id. */
  int WRITE = 27;
  /** RegularExpression Id. */
  int XECUTE = 28;
  /** RegularExpression Id. */
  int F_ASCII = 29;
  /** RegularExpression Id. */
  int F_CHAR = 30;
  /** RegularExpression Id. */
  int F_DATA = 31;
  /** RegularExpression Id. */
  int F_EXTRACT = 32;
  /** RegularExpression Id. */
  int F_FIND = 33;
  /** RegularExpression Id. */
  int F_FNUMBER = 34;
  /** RegularExpression Id. */
  int F_GET = 35;
  /** RegularExpression Id. */
  int F_JUSTIFY = 36;
  /** RegularExpression Id. */
  int F_LENGTH = 37;
  /** RegularExpression Id. */
  int F_NAME = 38;
  /** RegularExpression Id. */
  int F_ORDER = 39;
  /** RegularExpression Id. */
  int F_PIECE = 40;
  /** RegularExpression Id. */
  int F_QLENGTH = 41;
  /** RegularExpression Id. */
  int F_QSUBSCRIPT = 42;
  /** RegularExpression Id. */
  int F_QUERY = 43;
  /** RegularExpression Id. */
  int F_RANDOM = 44;
  /** RegularExpression Id. */
  int F_REVERSE = 45;
  /** RegularExpression Id. */
  int F_SELECT = 46;
  /** RegularExpression Id. */
  int F_STACK = 47;
  /** RegularExpression Id. */
  int F_TEXT = 48;
  /** RegularExpression Id. */
  int F_TRANSLATE = 49;
  /** RegularExpression Id. */
  int F_VIEW = 50;
  /** RegularExpression Id. */
  int V_DEVICE = 51;
  /** RegularExpression Id. */
  int V_ECODE = 52;
  /** RegularExpression Id. */
  int V_ESTACK = 53;
  /** RegularExpression Id. */
  int V_HORLOG = 54;
  /** RegularExpression Id. */
  int V_IO = 55;
  /** RegularExpression Id. */
  int V_JOB = 56;
  /** RegularExpression Id. */
  int V_KEY = 57;
  /** RegularExpression Id. */
  int V_PRINCIPAL = 58;
  /** RegularExpression Id. */
  int V_QUIT = 59;
  /** RegularExpression Id. */
  int V_REFERENCE = 60;
  /** RegularExpression Id. */
  int V_STORAGE = 61;
  /** RegularExpression Id. */
  int V_SYSTEM = 62;
  /** RegularExpression Id. */
  int V_TEST = 63;
  /** RegularExpression Id. */
  int V_X = 64;
  /** RegularExpression Id. */
  int V_Y = 65;
  /** RegularExpression Id. */
  int SV_GLOBAL = 66;
  /** RegularExpression Id. */
  int SV_JOB = 67;
  /** RegularExpression Id. */
  int SV_LOCK = 68;
  /** RegularExpression Id. */
  int SV_ROUTINE = 69;
  /** RegularExpression Id. */
  int SV_SYSTEM = 70;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\\n\"",
    "\"\\r\\f\"",
    "<COMMENT>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "<EXTTEXT>",
    "<BREAK>",
    "<CLOSE>",
    "<DO>",
    "<ELSE>",
    "<FOR>",
    "<GOTO>",
    "<HALT>",
    "<IF>",
    "<JOB>",
    "<KILL>",
    "<LOCK>",
    "<MERGE>",
    "<NEW>",
    "<OPEN>",
    "<QUIT>",
    "<READ>",
    "<SET>",
    "<USE>",
    "<VIEW>",
    "<WRITE>",
    "<XECUTE>",
    "<F_ASCII>",
    "<F_CHAR>",
    "<F_DATA>",
    "<F_EXTRACT>",
    "<F_FIND>",
    "<F_FNUMBER>",
    "<F_GET>",
    "<F_JUSTIFY>",
    "<F_LENGTH>",
    "<F_NAME>",
    "<F_ORDER>",
    "<F_PIECE>",
    "<F_QLENGTH>",
    "<F_QSUBSCRIPT>",
    "<F_QUERY>",
    "<F_RANDOM>",
    "<F_REVERSE>",
    "<F_SELECT>",
    "<F_STACK>",
    "<F_TEXT>",
    "<F_TRANSLATE>",
    "<F_VIEW>",
    "<V_DEVICE>",
    "<V_ECODE>",
    "<V_ESTACK>",
    "<V_HORLOG>",
    "<V_IO>",
    "<V_JOB>",
    "<V_KEY>",
    "<V_PRINCIPAL>",
    "<V_QUIT>",
    "<V_REFERENCE>",
    "<V_STORAGE>",
    "<V_SYSTEM>",
    "<V_TEST>",
    "\"$X\"",
    "\"$Y\"",
    "<SV_GLOBAL>",
    "<SV_JOB>",
    "<SV_LOCK>",
    "<SV_ROUTINE>",
    "<SV_SYSTEM>",
    "\" \"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&SQL\"",
  };

}
